language: node_js
cache: node_modules
node_js: stable

# S: Build Lifecycle
install:
  - npm install

before_script:
   - export TZ='Asia/Shanghai'  
 # - npm install -g gulp

script:
  - hexo g
  
after_script:
  - cd ./public
  - git init
  - git config user.name "imcco"
  - git config user.email "ceek@vip.qq.com"
  - git add .
  - git commit -m "Deploy at $(date)."
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master
  - git config http.postBuffer 524288000
  - git push --force --quiet --set-upstream  https://laukei:${CO_TOKEN}@git.coding.net/laukei/laukei.coding.me.git master:master

# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/imcco/imcco.github.io.git
