language: node_js   #设置语言
node_js: stable     #设置相应的版本
cache:
    directories:
        - node_modules    #据说可以减少travis构建时间
before_install:
  - npm install -g hexo
  - npm install -g hexo-cli
install:
  - npm install   #安装hexo及插件
before_script:
  - export TZ='Asia/Shanghai'  
  - npm install -g mocha
  - git clone --branch master https://github.com/imcco/blog.git public
  
script:
  - hexo cl   #清除
  - hexo g   #生成
  
after_script:
  - cd ./public
  - git init
  - git config user.name "imcco"
  - git config user.email "ceek@vip.qq.com"
  - git add .
  - git commit -m "Deploy at $(date)."
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master
  - git config http.postBuffer 524288000
  - git push --force --quiet --set-upstream  https://laukei:${CO_TOKEN}@git.coding.net/laukei/laukei.coding.me.git master:master

# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/imcco/blog.git
